### PR TITLE
Added the measures # Impacted Adults and # Impacted Children.

### PR DESCRIPTION
**Pull request by marcusgraca**
This PR includes the metrics for impacted adults and children through the measures # Impacted Adults and # Impacted Children.

### CODE REVIEW

**Comment by LarsKemmann** [comment]
@marcusgraca FYI, I rebased this branch onto _main_, removed the places in _report.json_ where it conflicted with changes I had made on the "Family Engagement" page, and resolved the merge conflict of the DAX measures so that the changes we had made earlier today were included as well as the new measures you created for this PR. So, now the code review is _much_ easier. 😊

**Comment by LarsKemmann** [comment]
This is looking great! Now, to test it and ensure we release this bug-free, can you please:

1. Investigate the (anonymized) data and make sure this is correct?
image
In particular, I noticed one apparent quirk in the data/measures: in 2024 (through today), location 1 had 20 families supported but only 17 adults impacted. What's the story with the 3 other families?

2. Find and highlight examples of the following cases from the dataset to validate that the logic is correct (include screenshots of the filtered family and person tables showing the Family Name, Full Name, timeframe and any other applied filters, as well as the corresponding "# Impacted Adults"/"# Impacted Children" measures shown as cards next to that table):
    1. an adult that was impacted by an arrangement for the adult (i.e., a "Community Friending" or "Guest Agreement" arrangement)
    2. an adult that was impacted by an arrangement for one of that adult's children (i.e., an "Overnight Hosting" or "Day Hosting" or "Recurring Hosting")
    3. a child that was impacted by an arrangement for one of that child's parents
    4. a child that was impacted by an arrangement for that child
    5. a child that was impacted by an arrangement for one of that child's siblings

**Review by LarsKemmann — CHANGES_REQUESTED** [review]
The code looks good, this just needs testing. See [my previous comment](https://github.com/CareTogether/CareTogether-PowerBI/pull/20#issuecomment-2533477609).

**Comment by marcusgraca** [comment]
Hi Lars, 

Regarding the first topic: # of Families Supported vs # Impacted Adults: 

I performed the suggested validations and found a small issue in the formula. I had to add RELATEDTABLE with the Arrangement table to ensure that the filter for active arrangements worked correctly:

image

Now, we have 15 impacted adults at location 1 in 2024, and I already have identified the cause:

The "Adult or Child" column has some gaps, causing some families to consist solely of children. This results in 5 impacted families not being identified in the impacted adults count, as shown in the screenshot below:

image

**Comment by marcusgraca** [comment]
Regarding the 2nd question: 

1. 
image

2. 
image

3. 
image

4. 
image

5. 
image

**Comment by marcusgraca** [comment]
Regarding the 2nd question: 

1. 
image

2. 
image

3. 
image

4. 
image

5. 
image

**Comment by LarsKemmann** [comment]
Thank you _so_ much for the testing work on this. 😊 I'd like to make that part of our standard process for each new measure that we add. For now, documenting the tests on PRs (like you've done here) is enough; at some point early next year, we're going to want to start documenting the various tables, columns, and measures in the model in ways that will eventually help power users do more self-service BI. For that, it'll be super helpful to be able to go back to these test plans & test results, see exactly how to explain each measure, and then replicate that in documentation (we'll have a better way to anonymize the datasets at that point so we can use realistic fake names instead of these redactions).

**Pull request closed without merging**
