### PR TITLE
Feature/drillthrough engagement tabs

### PR DESCRIPTION
**Pull request by marcusgraca**
- Added the Family Engagement and Individual Engagement Drill Through tabs

### CODE REVIEW

**Comment by marcusgraca** [comment]
Testing the Family Engagement Details tab: 


The family ADULT_00 FAM_6ad6 Family has 6 assignments. Let's see the details of these assignments on the Drill Through page (in this tab, we expect to audit each assignment individually):

The main tab: 

image

The result: 

image

**Comment by marcusgraca** [comment]
Testing the Individual Engagement Details tab:

The person ADULT_00 FAM_550a has 4 assignments. Let's check the details of these assignments on the Drill Through tab (in this tab, we expect to audit each assignment individually):

The main tab: 

image


The results: 

image

**Comment by marcusgraca** [comment]
**NOTE:** Since we aim to visualize each assignment individually, we encountered the following issue: Power BI, by default, aggregates identical values, causing assignments with the same information to be combined into a single row. To work around this behavior, I added a measure (which counts the number of assignments, as the logic and relationships are contained within it) and the assignment ID. However, both are visually hidden from the end user.

**Comment by LarsKemmann** [comment]
Add the start & end date of the arrangement to the drill-through results table

**Pull request merged**
